name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build SwiftPM Package
      run: swift build -v
    - name: Build Xcode App Target
      run: xcodebuild -project SwiftBot.xcodeproj -scheme SwiftBot -configuration Debug -destination 'platform=macOS' CODE_SIGNING_ALLOWED=NO build
